<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" 
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" 
  xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <?php if(!empty($this->pages)): ?>
        <?php foreach($this->pages as $page) : ?>
            <url>
                <loc><?php echo $this->serverUrl($page->getRoute(), array($page->getSlug_field() => $page->getSlug() )); ?></loc> 
                <lastmod><?php echo $page->getModified(); ?></lastmod>
                <?php if(0) : ?>
                    <image:image>
                       <image:loc>http://example.com/image.jpg</image:loc> 
                    </image:image>
                <?php endif; ?>

                <?php if(0) : ?>
                    <video:video>
                      <video:content_loc>
                        http://www.example.com/video123.flv
                      </video:content_loc>
                      <video:player_loc allow_embed="yes" autoplay="ap=1">
                        http://www.example.com/videoplayer.swf?video=123
                      </video:player_loc>
                      <video:thumbnail_loc>
                        http://www.example.com/thumbs/123.jpg
                      </video:thumbnail_loc>
                      <video:title>Grilling steaks for summer</video:title>  
                      <video:description>
                        Get perfectly done steaks every time
                      </video:description>
                    </video:video>
                <?php endif; ?>

            </url>
        <?php endforeach; ?>
    <?php endif; ?>
</urlset>